platforms_username = {
    # "Twitter": "https://twitter.com/{username}",
    "GitHub": "https://github.com/{username}",
    "Instagram": "https://instagram.com/{username}",
    # "Facebook": "https://facebook.com/public/{username}",
    # "LinkedIn": "https://linkedin.com/in/{username}",
    # "Reddit": "https://reddit.com/u/{username}",
    # "Twitch": "https://twitch.tv/{username}",
    # "YouTube": "https://youtube.com/@{username}",
    # "Snapchat": "https://snapchat.com/add/{username}",
    # "Pinterest": "https://pinterest.com/{username}",
    # "Tumblr": "https://tumblr.com/{username}",
    # "Flickr": "https://flickr.com/photos/{username}",
    # "SoundCloud": "https://soundcloud.com/{username}",
    # "Spotify": "https://open.spotify.com/user/{username}",
    # "Vimeo": "https://vimeo.com/{username}",
    # "Behance": "https://www.behance.net/{username}",
    # "Dribbble": "https://dribbble.com/{username}",
    # "DeviantArt": "https://{username}.deviantart.com/",
    # "500px": "https://500px.com/{username}",
    # "Medium": "https://medium.com/@{username}",
    # "Quora": "https://www.quora.com/profile/{username}",
    # "Stack Overflow": "https://stackoverflow.com/users/{username}",
    # "GitLab": "https://gitlab.com/{username}",
    # "Bitbucket": "https://bitbucket.org/{username}",
    # "HackerRank": "https://www.hackerrank.com/{username}",
    # "CodePen": "https://codepen.io/{username}",
    # "Kaggle": "https://www.kaggle.com/{username}",
    # "Steam": "https://steamcommunity.com/id/{username}",
    # "Origin": "https://origin.com/id/{username}",
    # "Etsy": "https://www.etsy.com/shop/{username}",
    # "Amazon": "https://www.amazon.com/gp/profile/{username}",
    # "IMDb": "https://www.imdb.com/user/{username}",
    # "Goodreads": "https://www.goodreads.com/{username}",
    # "Last.fm": "https://www.last.fm/user/{username}",
    # "TripAdvisor": "https://www.tripadvisor.com/members/{username}",
    # "VSCO": "https://vsco.co/{username}",
    # "Ello": "https://ello.co/{username}",
    # "WeHeartIt": "https://weheartit.com/{username}",
    # "Couchsurfing": "https://www.couchsurfing.com/people/{username}",
    # "Zillow": "https://www.zillow.com/profile/{username}",
    # "Realtor.com": "https://www.realtor.com/realestateagents/{username}",
    # "Airbnb": "https://www.airbnb.com/users/show/{username}",
    # "Booking.com": "https://www.booking.com/profile/{username}",
    # "Duolingo": "https://www.duolingo.com/profile/{username}",
    # "Reddit (Subreddit)": "https://reddit.com/r/{username}",
    # "Discord": "https://discordapp.com/users/{username}",
    # "Foursquare": "https://foursquare.com/user/{username}",
    # "Wikipedia": "https://en.wikipedia.org/wiki/User:{username}",
    # "Wikimedia Commons": "https://commons.wikimedia.org/wiki/User:{username}",
    # "Wiktionary": "https://en.wiktionary.org/wiki/User:{username}",
    # "Wikibooks": "https://en.wikibooks.org/wiki/User:{username}",
    # "Wikiquote": "https://en.wikiquote.org/wiki/User:{username}",
    # "Wikisource": "https://en.wikisource.org/wiki/User:{username}",
    # "Wikiversity": "https://en.wikiversity.org/wiki/User:{username}",
    # "Wikihow": "https://www.wikihow.com/User:{username}",
    # "Metacritic": "https://www.metacritic.com/user/{username}",
    # "Rotten Tomatoes": "https://www.rottentomatoes.com/user/id/{username}",
    # "Letterboxd": "https://letterboxd.com/{username}",
    # "Discogs": "https://www.discogs.com/user/{username}",
    # "Bandcamp": "https://bandcamp.com/{username}",
    # "Mixcloud": "https://www.mixcloud.com/{username}",
    # "Tidal": "https://listen.tidal.com/{username}",
    # "Hulu": "https://www.hulu.com/profiles/{username}",
    # "Crunchyroll": "https://www.crunchyroll.com/user/{username}",
    # "NPR": "https://www.npr.org/people/{username}",
    # "New York Times": "https://www.nytimes.com/by/{username}",
    # "Washington Post": "https://www.washingtonpost.com/people/{username}",
    # "The Guardian": "https://www.theguardian.com/profile/{username}",
    # "BBC": "https://www.bbc.com/user/{username}",
    # "CNN": "https://edition.cnn.com/profiles/{username}",
    # "Fox News": "https://www.foxnews.com/person/{username}",
    # "Reuters": "https://www.reuters.com/journalists/{username}",
    # "Bloomberg": "https://www.bloomberg.com/authors/{username}",
    # "CNBC": "https://www.cnbc.com/{username}",
    # "Forbes": "https://www.forbes.com/sites/{username}",
    # "Business Insider": "https://www.businessinsider.com/author/{username}",
    # "The Verge": "https://www.theverge.com/users/{username}",
    # "TechCrunch": "https://techcrunch.com/author/{username}",
    # "Wired": "https://www.wired.com/author/{username}",
    # "Ars Technica": "https://arstechnica.com/author/{username}",
    # "National Geographic": "https://www.nationalgeographic.com/contributors/{username}",
    # "NASA": "https://www.nasa.gov/profiles/{username}",
    # "ESPN": "https://www.espn.com/nba/player/_/id/{username}",
    # "NFL": "https://www.nfl.com/players/{username}",
    # "NBA": "https://www.nba.com/player/{username}",
    # "MLB": "https://www.mlb.com/player/{username}",
    # "NHL": "https://www.nhl.com/player/{username}",
    # "UEFA": "https://www.uefa.com/uefachampionsleague/clubs/{username}",
    # "FIFA": "https://www.fifa.com/fifa-world-ranking/{username}",
    # "Olympics": "https://olympics.com/tokyo-2020/olympic-games/en/results/all-sports/athletes/{username}",
    # "World Athletics": "https://www.worldathletics.org/athletes/{username}",
    # "IMDb Pro": "https://pro.imdb.com/profile/{username}",
    # "Academia.edu": "https://www.academia.edu/{username}",
    # "ResearchGate": "https://www.researchgate.net/profile/{username}",
    # "Google Scholar": "https://scholar.google.com/citations?user={username}",
    # "Microsoft Academic": "https://academic.microsoft.com/profile/{username}",
    # "ORCID": "https://orcid.org/{username}",
    # "Scopus": "https://www.scopus.com/authid/detail.uri?authorId={username}",
    # "Publons": "https://publons.com/researcher/{username}",
    # "Mendeley": "https://www.mendeley.com/profiles/{username}",
    # "Semantic Scholar": "https://www.semanticscholar.org/author/{username}",
    # "Academic Tree": "https://academictree.org/{username}",
    # "IEEE Xplore": "https://ieeexplore.ieee.org/author/{username}",
    # "Springer": "https://link.springer.com/{username}",
    # "ScienceDirect": "https://www.sciencedirect.com/scientist/{username}",
    # "PLOS": "https://www.plos.org/profile/{username}",
    # "Nature": "https://www.nature.com/srep/{username}",
}

platforms_email = {
    "facebook": "https://www.facebook.com/search/top/?q={email}",
    "github": "https://github.com/search?q={email}",
    "twitter": "https://twitter.com/i/api/1.1/users/email_available.json?email={email}",
    "instagram": "https://www.instagram.com/accounts/account_recovery_send_ajax/email/",
    "linkedin": "https://www.linkedin.com/checkpoint/rp/request-password-reset-submit?email={email}",
    "snapchat": "https://accounts.snapchat.com/accounts/password_reset_request",
    "pinterest": "https://www.pinterest.com/password/reset/?email={email}",
    "reddit": "https://www.reddit.com/password/?email={email}",
}

platforms_api = {
    "Github": "https://github.com/search",
    "Mastodon": "https://mastodon.social/api/v2/search"
}
